### PR TITLE
Added Top User Per Language Per Location Feature

### PR DESCRIPTION
**Pull request by robertisandor**
I simply added to the topLocationService and modified the HomeController accordingly.

### CODE REVIEW

**Review by BaReinhard — COMMENTED** [review]
Awesome job Rob!

One thing I may suggest, and this is probably more a decision for the group. @MarioEsparza @travisrand.

With the large amount of calls to git-awards occassionally comes back with CORS errors.

We may just want to make 3 initially for the match portion.

* One to get the stars and username for the top 25 for the top language of the searcher. 
* Another, to get searchers star count. 
* And lastly one more for the top matchers star count. We can then do another each time the user checks the next match. It would be nice to be able to get this individual information for each language, but with the inconsistency of crossorigin.me providing proper header information it just doesn't seem feasible in a reliable way.

As far as the top 25 users for the location we can do that search when the user clicks on top 25? or however we choose to display this, but ideally this can be done in 1 call.

How it sits now I was able to get the proper console output maybe 1 out of every 4-5 attempts.

Do anyone else have any better ideas?

**Comment by robertisandor** [comment]
When you say the top 25 users for the location, do you mean for a given language? Because if we're going purely on the overall stars an individual has, then we need to make just 1 call like you mentioned, which is much easier and doesn't run into the CORS issue. But if we're finding the top user for a language in a given location, we have to find how many stars a given user has for, say JavaScript or C++, and that info is something that we can only get via a call for the individual user. 
That would mean, to find the top user for a particular language in a given location, we need to make 1 call to get all of the users and 1 call per user to get the stars count that that user has for a particular language, which sums to 31 calls if we're looking at 30 people. 

I'm cool with either way, although the overall stars of a user is much easier to get and requires fewer calls.

**Comment by BaReinhard** [comment]
Yeah i see what you mean, although if we are searching for a specific language I think it would be good to just give stars of the specific language, more so just because it is more consistent.

I tried again with the code you have and it seems to be working without any errors now. Not sure what happened, but I don't think that the sorting algorithm is working correctly, or I just don't know what the expect results should be for last console log.

Is it just top user on all found languages

**Comment by robertisandor** [comment]
Within a given location, yes. Right now, it looks for the top user of all languages in a given location based on the users there. Would you prefer that the algorithm look for the top users of just 1 language in a given area?

**Pull request closed without merging**
